// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	 int N = Integer.parseInt(args[0]);
	 double num = 0;
	 int higherThanHalf = 0;
	 int lowerThanHalf = 0;
	 for (int i = 0; i <= N; i++) {
		num =  Math.random();
		if (num > N) higherThanHalf++;
		else if (num <= N) lowerThanHalf++; 
	 }
	 System.out.println("> 0.5: " + higherThanHalf + " times");
		System.out.println("<= 0.5: " + lowerThanHalf + " times");

	if (higherThanHalf != 0 && lowerThanHalf != 0) {
		double ratio = (double) higherThanHalf / lowerThanHalf;
		System.out.println("Ratio: " + ratio );
	}
	}
}
